name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: python -m PyInstaller --windowed --onefile __main__.py
    - run: RENAME dist\__main__.exe drag.exe
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/drag.exe"
